<?php

namespace CodeEduUser\Repositories;

use Prettus\Repository\Eloquent\BaseRepository;
use Prettus\Repository\Criteria\RequestCriteria;
use CodeEduUser\Models\Role;

/**
 * Class CategoryRepositoryEloquent.
 *
 * @package namespace App\Repositories;
 */
class RoleRepositoryEloquent extends BaseRepository implements RoleRepository
{

    public function create(array $attributes)
    {
        $attributes['password'] = Role::generatePassword();
        $model = parent::create($attributes); // TODO: Change the autogenerated stub
        \UserVerification::generate($model);
        $subject = config('codeeduuser.email.user_created.subject');
        \UserVerification::emailView('codeeduuser::emails.user-created');
        \UserVerification::send($model, $subject);
        return $model;
    }

    public function update(array $attributes, $id)
    {
        if (isset($attributes['password'])) {
            $attributes['password'] = Role::generatePassword($attributes['password']);
        }

        return parent::update($attributes, $id); // TODO: Change the autogenerated stub
    }

    /**
     * Specify Model class name
     *
     * @return string
     */
    public function model()
    {
        return Role::class;
    }

    

    /**
     * Boot up the repository, pushing criteria
     */
    public function boot()
    {
        $this->pushCriteria(app(RequestCriteria::class));
    }

    public function listsWithMutators($column, $key = null)
    {
        // TODO: Implement listsWithMutators() method.
    }

    public function onlyTrashed()
    {
        // TODO: Implement onlyTrashed() method.
    }

    public function withTrashed()
    {
        // TODO: Implement withTrashed() method.
    }
}
